# **19CSE305: MACHINE LEARNING LAB 2**

PYTHON BASICS : EXCERCISES

ROLL NUMBER: CB.EN.U4CSE19004

In [ ]:
PYTHON BASIC EXCERSISE

1)Get two positive integers start and end from the user and write a Python program to print all Prime numbers in that Interval.
2) Given a list of strings( Entered by the user), write program to get a percentage share of each word in the strings list.
percentage := (Occurrence of a word / Total words) * 100
3)Check if  given number is Fibonacci number or not. Given an integer ‘n’( Entered by the user), write a Python function that returns true if n  is Fibonacci number else return false.
4)Write a program to check if all digits of a number divide it. Given a number n( Entered by the user), find whether all digits of n divide it or not.
5)Get a given array as input from the user and split it from a specified position, and move the first part of array add to the end.
example:
Input : {1, 2, 3, 4, 5}, k = 3
Output :{4,5,1,2,3}


NUMPY BASIC EXCERSISE

1) Create a 2D array of shape 4x5 that contains random decimal numbers between 3 and 10.
2) Create a randomly created 1D array and Convert it to a 2D array with 2 rows.
3) Given a NumPy array of temperature values, convert the values of Fahrenheit degrees into Centigrade degrees. 
4) Write a NumPy program to count the number of dimensions, number of elements and number of bytes for each element in a given array.
5) Write a NumPy program to extract third and fourth elements of the second and third rows from a given (3x4) array.



PYTHON BASIC EXCERSISE

1.

In [9]:
a = int(input("Enter the start number : "))
b = int(input("Enter the end number : "))
for i in range(a,b+1):
  if(i > 1):
    for j in range(2,i):
      if(i % j == 0 ):
        break
    else:
      print(i)
      



Enter the start number : 1
Enter the end number : 10
2
3
5
7


4.

In [11]:
n = int(input("enter the number: "))
def numcheck(n):
  while(n > 0):
    d = n%10
    if((d !=0 and n%d == 0) == False ):
      return False
    n = n//10
  return True
x = numcheck(n)
if (x):
  print("Divisible")
else:
  print("Not Divisible")

     


enter the number: 244
Divisible


Numpy Basic Exercise

1.

In [18]:
import numpy as np
arr = np.random.randint(3,10,(4,5))
print(arr)


[[8 4 6 9 4]
 [7 9 6 4 3]
 [7 7 7 3 3]
 [9 3 5 9 3]]


2.

In [19]:
arr = np.random.randint(0,10,(10))
print(arr)
arr.reshape(2,5)

[0 5 0 6 2 1 5 2 8 6]


array([[0, 5, 0, 6, 2],
       [1, 5, 2, 8, 6]])

3.

In [23]:
arr = [100,105,109,107,210]
arr = np.array(arr)
c = [(f - 32)*5/9 for f in arr]
print(c)

[37.77777777777778, 40.55555555555556, 42.77777777777778, 41.666666666666664, 98.88888888888889]


4.

In [13]:
import numpy as np
arr = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
print(arr)
print("Dimensions: ")
print(arr.ndim)
print("Elements: ")
print(arr.size)
print("Size of element: ")
print(arr.itemsize)

[[1 2 3]
 [3 4 5]
 [4 5 6]]
Dimensions: 
2
Elements: 
9
Size of element: 
8


5.

In [26]:
import numpy as np
arr = np.arange(1,13)
arr = arr.reshape(3,4)
print(arr)
print(arr[1:3,2:4])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 7  8]
 [11 12]]
